apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::872949394813:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-10NJZIBTUSRD
      username: system:node:{{EC2PrivateDNSName}}  
    - groups:
      - system:masters    
      rolearn: arn:aws:iam::872949394813:role/UdacityFlaskDeployCBKubectlRole
      username: build 
  mapUsers: |
    []
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::872949394813:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-10NJZIBTUSRD\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2022-11-09T13:51:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "21339"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fdff23be-b828-44c8-8f8c-8218a8c4e319
